### ISSUE TITLE
Over resource limits on Streamlit Cloud

### ISSUE THREAD

**Issue by zhafen** [simonguichandut/WhyIsMyFlightLate#1]
Hey there :wave: Just wanted to let you know that [your app on Streamlit Cloud deployed from this repo](https://willmyflightbelate.streamlit.app/simonguichandut/whyismyflightlate/main) has gone over its resource limits. Access to the app is temporarily limited. Visit the app to see more details and possible solutions.

**Comment by simonguichandut** [comment]
Thanks for the warning! We implemented caching, it should be better now.
